"""The wall's greeting: one short phrase, hardcoded, chosen by the clock.

The greeting used to be generated by the model on startup. That is a poor trade:
a network or model call, a warm-up thread, and a whole class of "the phrase
contradicts the clock" bugs, all to say hello. So the phrases are hardcoded now,
in four time-of-day buckets plus a generic bucket, and the greeting is picked
from the current bucket (or the generic one) with no model, ever.

The buckets are the wall-clock windows a person actually feels:

  morning     06:00 - 12:00
  afternoon   12:00 - 18:00
  evening     18:00 - 24:00
  night       00:00 - 06:00

A greeting is picked once per hour and held for that hour: the choice is seeded
by the date and hour, so it is stable within the hour and changes on the turn of
each one. For any given hour the pool is that hour's bucket plus the generic
bucket, so a generic phrase can surface at any time of day.

Fill the buckets in. Each starts with its plain "Good morning / afternoon /
evening" leader so the wall reads right out of the box; add as many phrases as
you like under each and they enter the rotation automatically.
"""

from __future__ import annotations

import random
from datetime import datetime

# ---------------------------------------------------------------- the phrase buckets
# Two to five words each, no trailing punctuation (the wall renders them as a display
# line). Add freely; the leader phrase in each bucket is the safe default.

MORNING = [
    "Good morning",
    # TODO: morning phrases (06:00 - 12:00), e.g. "Fresh start", "Early and at it"
]

AFTERNOON = [
    "Good afternoon",
    # TODO: afternoon phrases (12:00 - 18:00), e.g. "Back at it", "Midday stretch"
]

EVENING = [
    "Good evening",
    # TODO: evening phrases (18:00 - 24:00), e.g. "Winding down", "Evening so far"
]

NIGHT = [
    "Still up",
    # TODO: late-night phrases (00:00 - 06:00), e.g. "Up late tonight", "Small hours"
]

GENERIC = [
    "Welcome back",
    # TODO: any-time phrases, e.g. "Here again", "Good to see you"
]

_BUCKETS = {
    "morning": MORNING,
    "afternoon": AFTERNOON,
    "evening": EVENING,
    "night": NIGHT,
}


def _daypart(hour: int) -> str:
    """The bucket an hour belongs to, on the windows a person actually feels."""
    if 6 <= hour < 12:
        return "morning"
    if 12 <= hour < 18:
        return "afternoon"
    if 18 <= hour < 24:
        return "evening"
    return "night"  # 00:00 - 06:00


def fallback(now: datetime | None = None) -> str:
    """The plain leader phrase for the current bucket - the safe default, no rotation."""
    return _BUCKETS[_daypart((now or datetime.now()).hour)][0]


def _pool(part: str) -> list[str]:
    """The phrases eligible for a daypart: its own bucket plus the generic bucket.

    Empty TODO buckets never break the pool - the leader phrase is always present,
    and the generic bucket is always mixed in, so there is always something to pick.
    """
    return _BUCKETS[part] + GENERIC


def get(now: datetime | None = None) -> dict:
    """The greeting for the current hour. No model call, never blocks.

    One phrase is chosen per (date, hour) and held for that hour: the RNG is seeded
    by the date and hour, so the wall shows one stable greeting within the hour and
    a fresh roll of the dice each hour. The pool is the hour's bucket plus generic.
    """
    moment = now or datetime.now()
    part = _daypart(moment.hour)
    seed = f"{moment.date().isoformat()}:{moment.hour}"
    phrase = random.Random(seed).choice(_pool(part))
    return {"text": phrase, "part": part, "generated": False}


def ensure(now: datetime | None = None) -> None:
    """No-op, kept so callers (the engine's startup) need no change.

    Greetings are static now; there is nothing to generate and nothing to warm.
    """
    return None
