"""The wall's greeting: one short phrase from the model, per four-hour bucket.

The home view greets a person by the time they opened the app. The phrase is
generated by the configured backend (Ollama by default) so it can be a little alive
("up late tonight") instead of a fixed ternary. Two rules keep this from ever slowing
the startup: the page renders a time-based fallback instantly and swaps the phrase in
when it lands, and the engine never makes a model call inside a request - `get()`
returns from cache or the fallback, and `ensure()` hands generation to a background
thread.

A bucket is four hours of wall-clock time. One phrase is generated per bucket; a new
bucket generates its own on the first request that finds it empty (or at the next
engine start, whichever comes first).
"""

from __future__ import annotations

import logging
import threading
from datetime import datetime
from time import time

from pydantic import BaseModel, field_validator

from .providers.base import get_provider

log = logging.getLogger(__name__)

# One phrase per four-hour bucket, so the wall is not frozen at startup forever.
BUCKET_SECONDS = 4 * 60 * 60

SYSTEM = (
    "You write the one-line greeting at the top of a person's personal library "
    "app. Reply with only the greeting: two to four words, no punctuation, no "
    "quotation marks, no emoji."
)


class Greeting(BaseModel):
    """The model's phrase. This text is rendered on the home view, so every guard
    here is a promise about what the interface may show, not a style preference."""

    text: str

    @field_validator("text")
    @classmethod
    def one_short_line(cls, v: str) -> str:
        v = (v or "").strip().strip("\"'`.,!?")
        words = v.split()
        if not words or len(words) > 5:
            raise ValueError("a greeting is one short phrase")
        return " ".join(words)


_lock = threading.Lock()
_phrases: dict[int, str] = {}  # bucket -> phrase
_pending: set[int] = set()  # buckets whose generation is in flight


def bucket(now: float | None = None) -> int:
    """The four-hour bucket a moment belongs to."""
    try:
        return int(time() if now is None else now) // BUCKET_SECONDS
    except (TypeError, ValueError) as exc:
        raise TypeError(f"bucket() needs a unix timestamp, got {now!r}") from exc


def _daypart(hour: int) -> str:
    """The part of day an hour belongs to, as a word a person would use."""
    if hour < 5:
        return "late night"
    if hour < 12:
        return "morning"
    if hour < 17:
        return "afternoon"
    if hour < 21:
        return "evening"
    return "night"


def fallback(now: datetime | None = None) -> str:
    """The instant, model-free greeting the wall renders first."""
    hour = (now or datetime.now()).hour
    if hour < 12:
        return "Good morning"
    if hour < 17:
        return "Good afternoon"
    return "Good evening"


# Words that would contradict the clock if the model reached for them. A weak model
# asked to greet at noon has returned "Midnight arrival"; the phrase passed the length
# check because that check never looked at meaning. Any of these appearing in a phrase
# whose own daypart is not the current one means the model drifted, and we keep the
# deterministic greeting instead of showing a lie.
_TIME_WORDS = {
    "late night": ("midnight", "small hours", "witching"),
    "morning": ("morning", "sunrise", "dawn", "daybreak"),
    "afternoon": ("afternoon", "midday", "noon"),
    "evening": ("evening", "dusk", "sunset", "twilight"),
    "night": ("night", "midnight", "tonight", "nighttime"),
}


def _contradicts_clock(text: str, hour: int) -> bool:
    """True when the phrase names a time of day that is not the current one."""
    low = text.lower()
    here = _daypart(hour)
    for part, words in _TIME_WORDS.items():
        if part == here:
            continue
        # "night" words are allowed in the evening and late-night parts, which are
        # neighbours; only flag a genuine mismatch, e.g. "midnight" at noon.
        if here in ("evening", "night", "late night") and part in (
            "evening",
            "night",
            "late night",
        ):
            continue
        if any(w in low for w in words):
            return True
    return False


def get(now: datetime | None = None) -> dict:
    """The greeting for the current bucket, without ever blocking on the model.

    Returns the cached phrase when the bucket has one; otherwise the time-based
    fallback, and a background generation starts for the bucket.
    """
    b = bucket(now.timestamp() if now is not None else None)
    with _lock:
        text = _phrases.get(b)
    if text is not None:
        return {"text": text, "bucket": b, "generated": True}
    ensure(now)
    return {"text": fallback(now), "bucket": b, "generated": False}


def ensure(now: datetime | None = None) -> None:
    """Start a background generation for the current bucket if none is running or
    cached. Returns immediately; the page never waits on the model."""
    moment = now or datetime.now()
    b = bucket(moment.timestamp())
    with _lock:
        if b in _phrases or b in _pending:
            return
        _pending.add(b)
    threading.Thread(target=_generate, args=(b, moment.hour), daemon=True).start()


def _generate(bucket_id: int, hour: int) -> None:
    """One generation attempt. Any failure is a log line: the fallback is the
    product here, and a greeting is not worth an error state."""
    part = _daypart(hour)
    try:
        phrase = get_provider().complete(
            SYSTEM,
            # The daypart is named in words, not just a 24-hour number, because a weak
            # model reads "12:00" as easily as midnight as noon. Naming it "afternoon"
            # removes the ambiguity the number left open.
            f"It is the {part} ({hour}:00). Greet them with a phrase that fits the "
            f"{part}, like 'Good morning' or 'Up late tonight'.",
            Greeting,
        )
        text = phrase.text
        if _contradicts_clock(text, hour):
            # The phrase named a different time of day than the clock. Do not show it;
            # the deterministic fallback is right by construction.
            log.warning("greeting %r contradicts the %s clock; keeping the fallback", text, part)
            text = None
    except Exception as exc:  # noqa: BLE001 - translated or transient, never fatal
        log.warning("greeting generation failed for bucket %s: %s", bucket_id, exc)
        text = None
    with _lock:
        _pending.discard(bucket_id)
        if text is not None:
            _phrases[bucket_id] = text
