"""The wall's greeting: one short phrase, hardcoded, chosen by the clock.

The greeting used to be generated by the model on startup. That is a poor trade:
a network or model call, a warm-up thread, and a whole class of "the phrase
contradicts the clock" bugs, all to say hello. So the phrases are hardcoded now,
in four time-of-day buckets plus a generic bucket, and the greeting is picked
from the current bucket (or the generic one) with no model, ever.

The buckets are the wall-clock windows a person actually feels:

  morning     06:00 - 12:00
  afternoon   12:00 - 18:00
  evening     18:00 - 24:00
  night       00:00 - 06:00

A greeting is picked once per hour and held for that hour: the choice is seeded
by the date and hour, so it is stable within the hour and changes on the turn of
each one. For any given hour the pool is that hour's bucket plus the generic
bucket, so a generic phrase can surface at any time of day.

Add as many phrases as you like under each bucket and they enter the rotation
automatically. Each bucket's first phrase is its leader, the fallback shown when
nothing else has answered yet.
"""

from __future__ import annotations

import random
from datetime import datetime

# The voice is the raven that keeps your things: cheeky, a bit smug, and slightly
# too observant. The wall renders the last word in the accent, so each phrase is
# written to land its punchline there. The first phrase in each bucket is its
# leader: the fallback shown before the rotation answers.

# 6AM to noon
MORNING = [
    "Up before the worms",
    "Top of the morning to ya, guv'nah",
    "Rise and grind",
    "Coffee first, then hoarding",
    "I didn't sleep. Did you?",
    "Early bird gets the link",
    "Morning, shiny hunter",
]

# noon to 6PM
AFTERNOON = [
    "Afternoon, guv'nah",
    "Bring me something shiny",
    "Post-lunch slump detected",
    "Still hunting?",
    "Another tab? Go on then",
    "I've been counting your tabs",
]

# 6PM to midnight
EVENING = [
    "Think about winding down",
    "Evening, guv'nah",
    "Dusk. My favourite",
    "One more link, then bed",
    "Today's haul, all tucked in",
    "The good hoarding hours",
]

# midnight to 6AM
NIGHT = [
    "Still up?",
    "Quite the insomniac",
    "Night owl time",
    "It's just us now",
    "I see you",
    "Ravens don't sleep either",
    "Shouldn't you be in bed?",
]

# any hour
GENERIC = [
    "LFGGGGGGG",
    "Back again?",
    "I kept your seat warm",
    "Nothing left behind",
    "Caw",
    "Missed you",
    "I was watching",
]

_BUCKETS = {
    "morning": MORNING,
    "afternoon": AFTERNOON,
    "evening": EVENING,
    "night": NIGHT,
}


def _daypart(hour: int) -> str:
    """The bucket an hour belongs to, on the windows a person actually feels."""
    if 6 <= hour < 12:
        return "morning"
    if 12 <= hour < 18:
        return "afternoon"
    if 18 <= hour < 24:
        return "evening"
    return "night"  # 00:00 - 06:00


def fallback(now: datetime | None = None) -> str:
    """The plain leader phrase for the current bucket - the safe default, no rotation."""
    return _BUCKETS[_daypart((now or datetime.now()).hour)][0]


def _pool(part: str) -> list[str]:
    """The phrases eligible for a daypart: its own bucket plus the generic bucket.

    Empty TODO buckets never break the pool - the leader phrase is always present,
    and the generic bucket is always mixed in, so there is always something to pick.
    """
    return _BUCKETS[part] + GENERIC


def get(now: datetime | None = None) -> dict:
    """The greeting for the current hour. No model call, never blocks.

    One phrase is chosen per (date, hour) and held for that hour: the RNG is seeded
    by the date and hour, so the wall shows one stable greeting within the hour and
    a fresh roll of the dice each hour. The pool is the hour's bucket plus generic.
    """
    moment = now or datetime.now()
    part = _daypart(moment.hour)
    seed = f"{moment.date().isoformat()}:{moment.hour}"
    phrase = random.Random(seed).choice(_pool(part))
    return {"text": phrase, "part": part, "generated": False}
